added schema and seeds
Irroc/arcade-manager pull request #3
Opened 2024-01-20 18:34 UTC by Irroc

- added new database to schema that's more appropriate
- added tables for users, locations, and games
- made all model names plural to match new tables when frozen
- changed project.js in models to be games.js and made the content reflect that by adding the correct data parameters to the model
- added location.js to models and filled out the correct parameters for that model
- added new location model to index.js in models
- added the foreign keys parameters between games and location
- added gameData.json and locationData.json with all the pre loaded games and locations in it
- changed seed.js in seeds to bulk create the three tables

2024-01-20 20:56 UTC, AdamLSmith1984 requested changes
.

2024-01-20 21:02 UTC, SPCSanti1990 approved these changes

2024-01-20 21:04 UTC, AdamLSmith1984 approved these changes

2024-01-20 21:20 UTC, AdamLSmith1984 approved these changes

2024-01-21 20:27 UTC, SPCSanti1990 approved these changes
.

2024-01-21 20:39 UTC, SPCSanti1990 approved these changes

2024-01-21 21:12 UTC, merged